trigger:
  batch: true
  branches:
    include:
      - stage
  paths:
    include:
      - ops/api
      - apps/raven-api

pr:
  branches:
    include:
      - stage
  paths:
    include:
      - apps/raven-api

pool:
  vmImage: ubuntu-22.04

variables:
  APP_SERVICE_NAME: as-wa-mub-raven-stage
  APP_STARTUP_CMD: 'node /app/main.js'
  RESOURCE_MANAGER_CONN: rm-mub-raven-stage
  CONTAINER_REGISTRY_CONN: acr-mub-raven-stage
  CONTAINER_REGISTRY_SERVER: acrmubravenstage.azurecr.io
  DOCKER_REPOSITORY: wa/api
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/stage')]
  # workaround for Azure docker job warnings when new version of Docker is used in the self-hosted agent
  DOCKER_BUILDKIT: 1

steps:
  - template: tpl/steps.template.yml
