trigger:
  batch: true
  branches:
    include:
      - prod
  paths:
    include:
      - ops/api
      - apps/raven-api

pr:
  branches:
    include:
      - prod
  paths:
    include:
      - apps/raven-api

pool:
  vmImage: ubuntu-22.04

variables:
  APP_SERVICE_NAME: app-raven-prod-uks # as-wa-mub-raven-api-prod
  APP_STARTUP_CMD: 'node /app/main.js'
  RESOURCE_MANAGER_CONN: rm-mub-raven-prod
  CONTAINER_REGISTRY_CONN: acrravenproduks
  CONTAINER_REGISTRY_SERVER: acrravenproduks.azurecr.io
  DOCKER_REPOSITORY: wa/api
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  # workaround for Azure docker job warnings when new version of Docker is used in the self-hosted agent
  DOCKER_BUILDKIT: 1

steps:
  - template: tpl/steps.template.yml
