export const lastFundingTypes = [
  'Angel',
  'Convertible Note',
  'Corporate Round',
  'Debt Financing',
  'Equity Crowdfunding',
  'Grant',
  'Initial Coin Offering',
  'Non Equity Assistance',
  'Post Ipo Debt',
  'Post Ipo Equity',
  'Post Ipo Secondary',
  'Pre Seed',
  'Private Equity',
  'Product Crowdfunding',
  'Secondary Market',
  'Seed',
  'Series A',
  'Series B',
  'Series C',
  'Series D',
  'Series E',
  'Series F',
  'Series G',
  'Series H',
  'Series I',
  'Series J',
  'Series Unknown',
  'Undisclosed',
] as const;

export type LastFundingType = (typeof lastFundingTypes)[number];

export const dealRoomLastFundingTypes = [
  'ACQUISITION',
  'ANGEL',
  'BUYOUT',
  'CONVERTIBLE',
  'CORPORATE SPINOUT',
  'DEBT',
  'EARLY VC',
  'GRANT',
  'GROWTH EQUITY NON VC',
  'GROWTH EQUITY VC',
  'ICO',
  'IPO',
  'LATE VC',
  'LENDING CAPITAL',
  'MEDIA FOR EQUITY',
  'MERGER',
  'POST IPO CONVERTIBLE',
  'POST IPO DEBT',
  'POST IPO EQUITY',
  'POST IPO SECONDARY',
  'PRIVATE PLACEMENT NON VC',
  'PRIVATE PLACEMENT VC',
  'PROJECT, REAL ESTATE, INFRASTRUCTURE FINANCE',
  'SECONDARY',
  'SEED',
  'SERIES A',
  'SERIES B',
  'SERIES C',
  'SERIES D',
  'SERIES E',
  'SERIES F',
  'SERIES G',
  'SERIES H',
  'SPAC IPO',
  'SPAC PRIVATE PLACEMENT',
  'SPINOUT',
  'SUPPORT PROGRAM',
] as const;

export type DealRoomLastFundingType = (typeof dealRoomLastFundingTypes)[number];
