export type LastFundingType =
  | 'Angel'
  | 'Convertible Note'
  | 'Corporate Round'
  | 'Debt Financing'
  | 'Equity Crowdfunding'
  | 'Grant'
  | 'Initial Coin Offering'
  | 'Non Equity Assistance'
  | 'Post Ipo Debt'
  | 'Post Ipo Equity'
  | 'Post Ipo Secondary'
  | 'Pre Seed'
  | 'Private Equity'
  | 'Product Crowdfunding'
  | 'Secondary Market'
  | 'Seed'
  | 'Series A'
  | 'Series B'
  | 'Series C'
  | 'Series D'
  | 'Series E'
  | 'Series F'
  | 'Series G'
  | 'Series H'
  | 'Series I'
  | 'Series J'
  | 'Series Unknown'
  | 'Undisclosed';
