trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - ops/client
      - apps/raven-client
      - libs/rvnc-*
      - libs/rnvs-*

pr:
  branches:
    include:
      - main
  paths:
    include:
      - apps/raven-client
      - libs/rvnc-*
      - libs/rnvs-*

pool:
  vmImage: ubuntu-22.04

variables:
  RESOURCE_MANAGER_CONN: rm-mub-raven-dev
  RESOURCE_GROUP: Raven_DEV
  FRONT_CONFIGURATION: development
  FRONT_CDN_STORAGE_ACCOUNT_NAME: sauksmcravenwwwdev
  FRONT_CDN_ENDPOINT_NAME: fd-ep-www-mc-raven-dev
  FRONT_CDN_PROFILE_NAME: fd-mc-raven-dev
  PUBLICLY_AVAILABLE: false
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - template: tpl/steps.template.yml
