trigger:
  batch: true
  branches:
    include:
      - prod
  paths:
    include:
      - ops/client
      - apps/raven-client

pr:
  branches:
    include:
      - prod
  paths:
    include:
      - apps/raven-client

pool: Raven - Prod

variables:
  RESOURCE_MANAGER_CONN: rm-mub-raven-prod
  RESOURCE_GROUP: rg-mub-raven-prod
  FRONT_CONFIGURATION: production
  FRONT_CDN_STORAGE_ACCOUNT_NAME: stmubravenprodcdn
  FRONT_CDN_ENDPOINT_NAME: mub-raven-prod
  FRONT_CDN_PROFILE_NAME: cdn-mub-raven-prod
  PUBLICLY_AVAILABLE: true
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/prod')]

steps:
  - template: tpl/steps.template.yml
