trigger:
  batch: true
  branches:
    include:
      - prod
  paths:
    include:
      - ops/client
      - apps/raven-client

pr:
  branches:
    include:
      - prod
  paths:
    include:
      - apps/raven-client

pool:
  vmImage: ubuntu-22.04

variables:
  RESOURCE_MANAGER_CONN: rm-mub-raven-prod
  RESOURCE_GROUP: Raven_Staging
  FRONT_CONFIGURATION: production
  FRONT_CDN_STORAGE_ACCOUNT_NAME: sauksmcravenwwwprod
  FRONT_CDN_ENDPOINT_NAME: fd-ep-as-wa-mc-raven-staging
  FRONT_CDN_PROFILE_NAME: feazfdmcat
  PUBLICLY_AVAILABLE: false
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - template: tpl/steps.template.yml
