trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - ops/client
      - apps/raven-client

pr:
  branches:
    include:
      - main
  paths:
    include:
      - apps/raven-client

pool:
  vmImage: ubuntu-22.04

variables:
  RESOURCE_MANAGER_CONN: rm-mub-raven-dev
  RESOURCE_GROUP: rg-mub-raven-dev
  FRONT_CONFIGURATION: development
  FRONT_CDN_STORAGE_ACCOUNT_NAME: stmubravendevcdn
  FRONT_CDN_ENDPOINT_NAME: mub-raven-dev
  FRONT_CDN_PROFILE_NAME: cdn-mub-raven-dev
  PUBLICLY_AVAILABLE: false
  SHOULD_DEPLOY: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

steps:
  - template: tpl/steps.template.yml
